version: "2"
services:
  app:
    build: .
    environment:
      RACK_ENV: development
      COOKIE_SECRET: foobar
      AUTH_TOKEN: foobar
      AAD_CLIENT_ID: ${AAD_CLIENT_ID}
      AAD_TENANT: ${AAD_TENANT}
      FORECAST_API_KEY: ${FORECAST_API_KEY}
      FORECAST_LOCATION: 41.448170,-72.804079
      JIRA_URL: https://cagedata.atlassian.net
      JIRA_USERNAME: ${JIRA_USERNAME}
      JIRA_PASSWORD: ${JIRA_PASSWORD}
      JIRA_FILTER: 10300
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET}
      TWITTER_SEARCH: '#devops'
      VICTOROPS_ID: ${VICTOROPS_ID}
      VICTOROPS_KEY: ${VICTOROPS_KEY}
      VICTOROPS_ORG: ${VICTOROPS_ORG}
      VICTOROPS_USERNAME: ${VICTOROPS_USERNAME}
      VICTOROPS_PASSWORD: ${VICTOROPS_PASSWORD}
    volumes:
      - .:/app
    ports:
      - "3030:3030"
